### ISSUE TITLE
Add CentOS 8 support for ansible-nginx-hardening

### ISSUE THREAD

**Issue by rndmh3ro** [dev-sec/ansible-nginx-hardening#25]
We'd like to support CentOS8!

Ideally we'd have testing for:

* kitchen with vagrant (https://github.com/dev-sec/ansible-nginx-hardening/blob/master/.kitchen.vagrant.yml)
* kitchen with docker (https://github.com/dev-sec/ansible-nginx-hardening/blob/master/.kitchen.yml)
* travis (https://github.com/dev-sec/ansible-nginx-hardening/blob/master/.travis.yml)

Docker-Image that should be used: https://cloud.docker.com/repository/docker/rndmh3ro/docker-centos8-ansible

**Comment by schurzi** [comment]
Testing on CentOS8 is includet in our collection Port: https://github.com/dev-sec/ansible-os-hardening/pull/291

This seems redundant now
