### ISSUE TITLE
ssl_dhparam

### ISSUE THREAD

**Issue by RatoX** [dev-sec/ansible-nginx-hardening#4]
Hi everyone,

I've been using this repo to help harden my stuff ( thank you for that!!! )
I'm using these roles too:

- jdauphant/ansible-role-nginx
- jdauphant/ansible-role-ssl-certs

And then when I run your role to harden my server,  I get this error:

`nginx: [emerg] BIO_new_file("/etc/nginx/2048") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/2048','r') error:2006D080:BIO routines:BIO_new_file:no such file)`

I took at look at your code and I saw this line

I'm not very good with NGINX configuration but it sounds to me a misunderstanding when you set the ssl_dhparam param.

Thank you for this role and sorry for anything

**Comment by rndmh3ro** [comment]
Thanks for reporting this! I'll fix this soon!
