### ISSUE TITLE
Syntax Error while loading YAML in defaults/main.yml

### ISSUE THREAD

**Issue by ahrib** [dev-sec/ansible-nginx-hardening#6]
Have put the role in a playbook and receive the below error. 

```
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/roles/dev-sec.nginx-hardening/defaults/main.yml': line 16, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    # vvoid clickjacking
	"X-Frame-Options SAMEORIGIN",
^ here
```

ansible-nginx-hardening v1.0.1
ansible 2.1.2.0

**Comment by rndmh3ro** [comment]
Thats weird. I'm not having this issue. What OS are you using?

What happens when you remove the comments and spaces in the defaults.yml:

```
nginx_add_header: [
"X-Frame-Options SAMEORIGIN",
"X-Content-Type-Options nosniff",
"X-XSS-Protection \"1; mode=block\"" ]
```

**Comment by ahrib** [comment]
I'm on OS X.

Figured it out, seems it was grumpy about the tab characters. Changed the tabs to 4 spaces and all OK.

**Comment by rndmh3ro** [comment]
Thanks, I'll remove these!
