### ISSUE TITLE
nginx_limit_conn default 5 seems to be too restrictive

### ISSUE THREAD

**Issue by shanx** [dev-sec/ansible-nginx-hardening#9]
`ansible-nginx-hardening/defaults/main.yml` defines a default `nginx_limit_conn: "default 5"` this makes us run into occasional `503 Service Temporarily Unavailable` on our nginx deploy. We have raised our default limit. But I'm wondering on what basis default 5 was chosen? To me it seems very restrictive.

**Comment by rndmh3ro** [comment]
Hey @shanx, would you mind raising this issue here: https://github.com/dev-sec/nginx-baseline?

The settings applied in this role are based on the compliance profile nginx-baseline.

**Comment by rndmh3ro** [comment]
Since that setting is a default value and can be overridden, I'll close this for now. Further discussions should happen in the baseline repo.
